SELECT ADDRESS
FROM STUDIO
WHERE NAME = "MGM";

SELECT BIRTHDATE
FROM MOVIESTAR
WHERE NAME = "Kim Basinger";

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > 10000000;

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M' or ADDRESS = "Prefect Rd";

INSERT INTO MOVIESTAR values ('Zahari Baharov', "Sofia", "M", '1979-07-05');
DELETE FROM STUDIO WHERE ADDRESS like '%5%';
UPDATE MOVIE
SET STUDIONAME = 'Fox'
WHERE TITLE like '%star%';

SELECT NAME
FROM MOVIESTAR
WHERE NAME in (SELECT STARNAME 
				FROM STARSIN
				WHERE MOVIETITLE = 'Terms of Endearment');

SELECT STARNAME
FROM STARSIN
WHERE MOVIETITLE in (SELECT TITLE
					FROM MOVIE
					WHERE STUDIONAME = 'MGM' and YEAR = 1995);

ALTER TABLE STUDIO
    ADD COLUMN president_name VARCHAR(50);

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH 
				FROM MOVIE
				WHERE TITLE = 'Gone With the Wind');

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > (SELECT NETWORTH
				 FROM MOVIEEXEC
				WHERE NAME =  'Merv Griffin');
